# Generated by Django 4.1.7 on 2023-04-20 16:44

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_unidadeproducao_created_unidadeproducao_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='username',
            field=models.CharField(error_messages={'unique': 'Já existe um utilizador com esse nome de utilizador.'}, help_text='Máximo 20 caracteres. Apenas letras, números e os seguintes símbolos @/./+/-/_ ', max_length=20, null=True, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()]),
        ),
    ]
